### ISSUE TITLE
[Suggestion] Add fake LMAOBOX spam

### ISSUE THREAD

**Issue by notchristopher** [nullifiedcat/cathook#92]
Suggestion: Add a feature that obtains a random player's name and fake the LMAOBOX spam with newlines and the obtained name, such as this:

`\n\n\n\n\n\n\n\n\n\n%name% :  GET GOOD, GET LMAOBOX`
`\n\n\n\n\n\n\n\n\n\n%name% :  LMAOBOX - WAY TO THE TOP`
`\n\n\n\n\n\n\n\n\n\n%name% :  WWW.LMAOBOX.NET - BEST TF2 HACKS!`

This should be a good trick to avoid votekicks when playing on casual.

**Comment by nullifiedcat** [comment]
I have another idea - instead of making this another cheat feature, extend spam one instead.
Add %variables% like in KillSay, for example:
`%enemyteam% %myteam% %me% %topteammate% %topenemy%` and extended one for random player selection:
`%player:s?(e|t)?(a|d)?%` where s = static (player will be picked and used until he leaves or doesn't match filters, e = enemy, t = teammate, a = alive, d = dead.

**Comment by nullifiedcat** [comment]
like, `%player:se%` will pick a random enemy and keep his name for future spam - allowing the LMAOBOX spam you asked for, `%player:e% is a noob` will make a simple insult spam for random enemies (re-rolled each time)

**Comment by nullifiedcat** [comment]
```
\n\n\n\n\n\n\n\n%query:se89%: GET GOOD, GET LMAOBOX!
```
(static enemy sniper/spy)
